server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:users;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
kafka:
  bootstrap-servers: kafka:9092
mail:
  from: no-reply@example.local
